
--1 Realiza Restore
--Procedimento...

--2 Cria usúario
USE [master]
GO
CREATE LOGIN [admcurso] WITH PASSWORD=N'123456' MUST_CHANGE, DEFAULT_DATABASE=[ERP_FOREST], 
          DEFAULT_LANGUAGE=[Português], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

--DESCOBRINDO SEU USUARIO LOGADO
SELECT SYSTEM_USER

--PERMISSÃO PARA USUARIO
USE master
GO
ALTER AUTHORIZATION ON DATABASE::ERP_FOREST TO [admcurso];

GO

