/* Qual total de vendas geral consolidado(geral) Mês À mÊs
	Tabelas envolvidas:
	NOTA_FISCAL
	EMPRESA
	##########################

	Regras tipo nota de venda saida = 'S'
	3552807.36
.
*/

-- Solução 1

SELECT A.FANTASIA,
		YEAR(B.DATA_EMISSAO)ANO,
		MONTH(B.DATA_EMISSAO)MES,
		SUM(B.TOTAL_NF) AS TOTAL
	FROM EMPRESA A
	INNER JOIN NOTA_FISCAL B
	ON A.COD_EMPRESA=B.COD_EMPRESA
	WHERE B.TIP_NF = 'S'
	GROUP BY A.FANTASIA, YEAR(B.DATA_EMISSAO), MONTH(B.DATA_EMISSAO)

-- SOLUÇÃO 2

SELECT A.FANTASIA,
		CONVERT(varchar(7), B.DATA_EMISSAO,111) ANO_MES, --YYYY-MM-DD
		SUM(B.TOTAL_NF) AS TOTAL
	FROM EMPRESA A
	INNER JOIN NOTA_FISCAL B
	ON A.COD_EMPRESA=B.COD_EMPRESA
	WHERE B.TIP_NF = 'S'
	GROUP BY A.FANTASIA, CONVERT(varchar(7), B.DATA_EMISSAO,111)

--SOLUCAO 3

SELECT ISNULL(A.FANTASIA, 'Total Geral') AS FANTASIA,
		ISNULL (CONVERT(varchar(7), B.DATA_EMISSAO,111), 'Total') AS ANO_MES, --YYYY-MM-DD
		SUM(B.TOTAL_NF) AS TOTAL
	FROM EMPRESA A
	INNER JOIN NOTA_FISCAL B
	ON A.COD_EMPRESA=B.COD_EMPRESA
	WHERE B.TIP_NF = 'S'
	GROUP BY ROLLUP (A.FANTASIA, CONVERT(varchar(7), B.DATA_EMISSAO,111))