/* 6. Qual o total de vendas geral consolidado por Linha de produto por empresa.
##### Tabelas envolvidas ######
# 
# NOTA_FISCAL
# NOTA_FISCAL_ITENS
# MATERIAL
# LINHA_PRODUTO
# EMPRESA
###############################

REGRAS TIPO DE NOTA DE VENDA SAIDA = 'S'
3552807.36
*/
-- SOLUCAO 1
	
SELECT E.FANTASIA AS EMPRESA, D.DESC_LINHA AS 'LINHA DE PRODUTO', SUM(B.QTD*round(B.VAL_UNIT, 2)) as TOTAL
FROM NOTA_FISCAL A
	INNER JOIN NOTA_FISCAL_ITENS B
	ON A.COD_EMPRESA=B.COD_EMPRESA
	AND A.NUM_NF=B.NUM_NF
	INNER JOIN MATERIAL C
	ON A.COD_EMPRESA=C.COD_EMPRESA
	AND B.COD_MAT=C.COD_MAT
	INNER JOIN LINHA_PRODUTO D
	ON A.COD_EMPRESA=D.COD_EMPRESA
	AND C.COD_LINHA=D.COD_LINHA
	INNER JOIN EMPRESA E
	ON A.COD_EMPRESA=E.COD_EMPRESA
	WHERE A.TIP_NF = 'S'
	GROUP BY D.DESC_LINHA, E.FANTASIA

	-- SOLUCAO 2
	
SELECT ISNULL(D.DESC_LINHA, 'TOTAL') LINHA_PRODUTO,
		ISNULL(E.FANTASIA, 'SUBTOT') EMPRESA, 
		SUM(B.QTD*B.VAL_UNIT) AS TOTAL 
FROM NOTA_FISCAL A
	INNER JOIN NOTA_FISCAL_ITENS B
	ON A.COD_EMPRESA=B.COD_EMPRESA
	AND A.NUM_NF=B.NUM_NF
	INNER JOIN MATERIAL C
	ON A.COD_EMPRESA=C.COD_EMPRESA
	AND B.COD_MAT=C.COD_MAT
	INNER JOIN LINHA_PRODUTO D
	ON A.COD_EMPRESA=D.COD_EMPRESA
	AND C.COD_LINHA=D.COD_LINHA
	INNER JOIN EMPRESA E
	ON A.COD_EMPRESA=E.COD_EMPRESA
	WHERE A.TIP_NF = 'S'
	GROUP BY ROLLUP(D.DESC_LINHA, E.FANTASIA)
	ORDER BY 1

