/* Qual total de vendas geral consolidado por SubCategoria de material
###### TABELAS ENVOLVIDAS #######
# 
# NOTA_FISCAL
# NOTA_FISCAL_ITENS
# MATERIAL
# SUB_CATEGORIA
#############################
REGRAS TIPO NOTA DE VENDA SAIDA = 'S'
3552807.36
*/
-- SOLUCAO 1
SELECT D.DESC_CATEGORIA, SUM(B.QTD*B.VAL_UNIT) TOTAL
FROM NOTA_FISCAL A
	INNER JOIN NOTA_FISCAL_ITENS B
	ON A.COD_EMPRESA=B.COD_EMPRESA
	AND A.NUM_NF=B.NUM_NF
	INNER JOIN MATERIAL C
	ON B.COD_EMPRESA=C.COD_EMPRESA
	AND B.COD_MAT=C.COD_MAT
	INNER JOIN SUB_CATEGORIA D
	ON C.COD_EMPRESA=D.COD_EMPRESA
	AND C.COD_CATEGORIA=D.COD_CATEGORIA
	WHERE A.TIP_NF = 'S'
	GROUP BY D.DESC_CATEGORIA

	-- SOLUCAO 2
SELECT ISNULL (D.DESC_CATEGORIA, 'TOTAL') SUB_CATG, 
		SUM(B.QTD*B.VAL_UNIT) TOTAL
FROM NOTA_FISCAL A
	INNER JOIN NOTA_FISCAL_ITENS B
	ON A.COD_EMPRESA=B.COD_EMPRESA
	AND A.NUM_NF=B.NUM_NF
	INNER JOIN MATERIAL C
	ON B.COD_EMPRESA=C.COD_EMPRESA
	AND B.COD_MAT=C.COD_MAT
	INNER JOIN SUB_CATEGORIA D
	ON C.COD_EMPRESA=D.COD_EMPRESA
	AND C.COD_CATEGORIA=D.COD_CATEGORIA
	WHERE A.TIP_NF = 'S'
	GROUP BY ROLLUP(D.DESC_CATEGORIA)